[package]
name = "demug-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
libdemug = {path = "../libdemug", features = ["debug"]}
winit = "0.30.10"
pixels = "0.15.0"
egui = "0.31.1"
egui-winit = "0.31.1"
egui-wgpu = { version = "0.31.1", features = ["winit"] }
egui_extras = "0.31.1"
pollster = "0.4.0"